### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by ownage2** [Johyuncheol/Our_ToDoList#13]
안녕하세요

독창적인 페이지 구성이 눈에 띄고 아주 멋있습니다. 라우터, 리덕스 등을 사용해서 기능 구현도 문제없이 잘 해내신 것 같습니다.

다만 아쉬운 부분들이 몇 몇 부분 보여서 이 부분들에 대해 코멘트 남깁니다
1. Header.js에서 Add버튼과 다르게 Todolist.js에서는 DeleteBtn 함수를 변수에 할당하신 것이 아쉽습니다. 일관성 있게 수정하면 보기 좋을 것 같습니다.
2. 상태 변경 방식을 조금 개선하면 어떨까요? 페이지 자체가 독창적인 것도 좋고, 저희가 당장에는 UX를 생각하며 구현을 하고 있지는 않지만 완료, 취소 버튼이 없어서 상세 페이지에서만 수정이 가능한 점은 아쉬운 것 같습니다.
3. 콘솔 로그 개선이 필요해 보입니다. 확인용으로 콘솔에 찍어보는 건 좋지만, 배포용 코드에서는 제거되는 게 맞는 듯 합니다. (사용자 정보 노출, 성능에 영향 줄 수 있음)
4. 현재 할 일 추가할 때 input에 문자를 입력할 때 마다 렌더링이 발생하고 있는데 개선이 필요해 보입니다.
5. 과제 요구 사항인 전체 화면의 크기(max-width, min-width) 지정을 깜빡하신 것 같습니다.

**Comment by Johyuncheol** [comment]
감사합니다 피드백 주신 내용으로 수정했습니다! ㅎㅎ
